[tool.black]
target-version = ["py310"]

[tool.ruff]
target-version = "py310"
select = [
    "F",   # pyflakes
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "I",   # isort
    "YTT", # flake8-2020
    "C",   # flake8-comprehensions
    "B",   # flake8-bugbear
]
fix = true
ignore = [
    "E501", # Black handles line limits
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.isort]
combine-as-imports = true

[tool.pyupgrade]
keep-runtime-typing = true

[tool.mypy]
python_version = "3.10"
show_error_codes = true
check_untyped_defs = true
no_implicit_reexport = false
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
warn_unused_configs = true
warn_unused_ignores = true
warn_redundant_casts = true

[[tool.mypy.overrides]]
module = ["voluptuous"]
ignore_missing_imports = true
