name: Validate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5.0.0
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.13
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5.0.0

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@72e1db9d29431ebc9439e48504e687b53e90d366 # master

  hacs: # https://github.com/hacs/action
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Run HACS validation
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: integration
          # Remove this 'ignore' key when you have added brand images for your integration to https://github.com/home-assistant/brands
          ignore: brands

  compare-string-files:
    name: Compare string files (ensure they are identical)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compare string file hashes
        id: strings-comparison
        run: |
          FILE1="${{ github.workspace }}/custom_components/wattbox/strings.json"
          FILE2="${{ github.workspace }}/custom_components/wattbox/translations/en.json"

          if [ ! -f "$FILE1" ]; then
            echo "Error: File 1 not found at $FILE1"
            exit 1
          fi
          if [ ! -f "$FILE2" ]; then
            echo "Error: File 2 not found at $FILE2"
            exit 1
          fi

          HASH1=$(md5sum "$FILE1" | awk '{print $1}')
          HASH2=$(md5sum "$FILE2" | awk '{print $1}')

          if [ "$HASH1" = "$HASH2" ]; then
            echo "Files are identical."
            echo "identical=true" >> "$GITHUB_OUTPUT"
            exit 0
          else
            echo "Files are NOT identical."
            echo "identical=false" >> "$GITHUB_OUTPUT"
            exit 1
          fi
        shell: bash